//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DomainTests.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaliyah
        ///aaren
        ///aarika
        ///aaron
        ///aartjan
        ///aarushi
        ///abagael
        ///abagail
        ///abahri
        ///abbas
        ///abbe
        ///abbey
        ///abbi
        ///abbie
        ///abby
        ///abbye
        ///abdalla
        ///abdallah
        ///abdul
        ///abdullah
        ///abe
        ///abel
        ///abi
        ///abia
        ///abigael
        ///abigail
        ///abigale
        ///abra
        ///abraham
        ///abram
        ///abree
        ///abrianna
        ///abriel
        ///abrielle
        ///abu
        ///aby
        ///acacia
        ///access
        ///accounting
        ///ace
        ///achal
        ///achamma
        ///action
        ///ada
        ///adah
        ///adair
        ///adalia
        ///adaline
        ///adalyn
        ///adam
        ///adan
        ///adara
        ///adda
        ///addi
        ///addia
        ///addie
        ///addilyn
        ///addison
        ///addons
        ///addy
        ///ade
        ///adel
        ///adela
        ///adelaida
        ///adelaide
        ///adele
        ///adelene
        ///adelheid
        ///adelia
        ///adelice
        ///adelina
        ///adelind
        ///adeline
        ///adella
        ///adelle
        ///adelynn
        ///aden
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string names {
            get {
                return ResourceManager.GetString("names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;aaliyah&quot;,&quot;aaren&quot;,&quot;aarika&quot;,&quot;aaron&quot;,&quot;aartjan&quot;,&quot;aarushi&quot;,&quot;abagael&quot;,&quot;abagail&quot;,&quot;abahri&quot;,&quot;abbas&quot;,&quot;abbe&quot;,&quot;abbey&quot;,&quot;abbi&quot;,&quot;abbie&quot;,&quot;abby&quot;,&quot;abbye&quot;,&quot;abdalla&quot;,&quot;abdallah&quot;,&quot;abdul&quot;,&quot;abdullah&quot;,&quot;abe&quot;,&quot;abel&quot;,&quot;abi&quot;,&quot;abia&quot;,&quot;abigael&quot;,&quot;abigail&quot;,&quot;abigale&quot;,&quot;abra&quot;,&quot;abraham&quot;,&quot;abram&quot;,&quot;abree&quot;,&quot;abrianna&quot;,&quot;abriel&quot;,&quot;abrielle&quot;,&quot;abu&quot;,&quot;aby&quot;,&quot;acacia&quot;,&quot;access&quot;,&quot;accounting&quot;,&quot;ace&quot;,&quot;achal&quot;,&quot;achamma&quot;,&quot;action&quot;,&quot;ada&quot;,&quot;adah&quot;,&quot;adair&quot;,&quot;adalia&quot;,&quot;adaline&quot;,&quot;adalyn&quot;,&quot;adam&quot;,&quot;adan&quot;,&quot;adara&quot;,&quot;adda&quot;,&quot;addi&quot;,&quot;addia&quot;,&quo....
        /// </summary>
        internal static string SerializedNames {
            get {
                return ResourceManager.GetString("SerializedNames", resourceCulture);
            }
        }
    }
}
